program: train.py 
method: bayes
name: para_sweep
metric:
  name: test_accuracy
  goal: maximize
parameters:
  model: 
    value: "vit"
  dataset: 
    value: "hutech-dataset:latest"
  scheduler: 
    values: ["reduce_lr_on_plateau", "cosine", "step", "cosine_warmup"]
  es_patience: 
    value: 10
  pretrained:
    value: True
  freeze:
    value: False

  ## optimizing
  lr:
    distribution: categorical
    values:
      - 0.00001
      - 0.00003
  momentum:
    distribution: uniform
    min: 0.5
    max: 1.5
  optimizer:
    distribution: categorical
    values:
      - adam
      - sgd
      - adamw
  batch_size: 
    values: [4, 8, 16]
  num_epochs: 
    values: [150]
  weight_decay:
    distribution: uniform
    min: 0.00004
    max: 0.0003
  normalize:
    values: [True, False]
  mean: 
    value: [0.485, 0.456, 0.406]
  std: 
    value: [0.229, 0.224, 0.225]


  ## augmentation
  resize:
    values: [224]
  horizontal_flip:
    values: [0.5]
  vertical_flip:
    values: [0.5]
  random_rotation:
    values: [90]
  # brightness:
  #   values: [0.5]
  # contrast:
  #   values: [1.0]
  # hue:
  #   values: [0.5]
  random_affine: 
    values: [0.2]
  random_perspective:
    values: [0.2]
  auto_aug:
    values: [1] 

command:
  - ${env}
  - python
  - ${program}